export default () => {
  const pathName = window.location.pathname
  const pathElements = pathName.split(`/`)
  // get rid of empty element at start
  pathElements.shift()
  return {
    projektFolder: pathElements[0] && pathElements[0] === `Projekte`,
    projekt: this.projektFolder && pathElements[1] ? pathElements[1] : null,
    apberuebersichtFolder: this.projekt && pathElements[2] && pathElements[2] === `AP-Berichte`,
    apberuebersicht: this.apberuebersichtFolder && pathElements[3] ? pathElements[3] : null,
    apFolder: this.projekt && pathElements[2] && pathElements[2] === `Arten`,
    ap: this.apFolder && pathElements[3] ? pathElements[3] : null,
    assozartFolder: this.ap && pathElements[4] && pathElements[4] === `assoziierte-Arten`,
    assozart: this.assozartFolder && pathElements[5] ? pathElements[5] : null,
    idealbiotopFolder: this.ap && pathElements[4] && pathElements[4] === `Idealbiotop`,
    beobNichtZuzuordnenFolder: this.ap && pathElements[4] && pathElements[4] === `nicht-zuzuordnende-Beobachtungen`,
    beobNichtZuzuordnen: this.beobNichtZuzuordnenFolder && pathElements[5] ? pathElements[5] : null,
    beobzuordnungFolder: this.ap && pathElements[4] && pathElements[4] === `nicht-beurteilte-Beobachtungen`,
    beobzuordnung: this.beobzuordnungFolder && pathElements[5] ? pathElements[5] : null,
    berFolder: this.ap && pathElements[4] && pathElements[4] === `Berichte`,
    ber: this.berFolder && pathElements[5] ? pathElements[5] : null,
    apberFolder: this.ap && pathElements[4] && pathElements[4] === `AP-Berichte`,
    apber: this.apberFolder && pathElements[5] ? pathElements[5] : null,
    erfkritFolder: this.ap && pathElements[4] && pathElements[4] === `AP-Erfolgskriterien`,
    erfkrit: this.erfkritFolder && pathElements[5] ? pathElements[5] : null,
    zielFolder: this.ap && pathElements[4] && pathElements[4] === `AP-Ziele`,
    ziel: this.zielFolder && pathElements[5] ? pathElements[5] : null,
    zielberFolder: this.ziel && pathElements[6] && pathElements[6] === `Berichte`,
    zielber: this.zielberFolder && pathElements[7] ? pathElements[7] : null,
    popFolder: this.ap && pathElements[4] && pathElements[4] === `Populationen`,
    pop: this.popFolder && pathElements[5] ? pathElements[5] : null,
    popberFolder: this.pop && pathElements[6] && pathElements[6] === `Kontroll-Berichte`,
    popber: this.popberFolder && pathElements[7] ? pathElements[7] : null,
    popmassnberFolder: this.pop && pathElements[6] && pathElements[6] === `Massnahmen-Berichte`,
    popmassnber: this.popmassnberFolder && pathElements[7] ? pathElements[7] : null,
    tpopFolder: this.pop && pathElements[6] && pathElements[6] === `Teil-Populationen`,
    tpop: this.tpopFolder && pathElements[7] ? pathElements[7] : null,
    tpopmassnFolder: this.tpop && pathElements[8] && pathElements[8] === `Massnahmen`,
    tpopmassn: this.tpopmassnFolder && pathElements[9] ? pathElements[9] : null,
    tpopmassnberFolder: this.tpop && pathElements[8] && pathElements[8] === `Massnahmen-Berichte`,
    tpopmassnber: this.tpopmassnberFolder && pathElements[9] ? pathElements[9] : null,
    tpopfeldkontrFolder: this.tpop && pathElements[8] && pathElements[8] === `Feld-Kontrollen`,
    tpopfeldkontr: this.tpopfeldkontrFolder && pathElements[9] ? pathElements[9] : null,
    tpopkontrzaehlFolder: this.tpopfeldkontr && pathElements[10] && pathElements[10] === `Zählungen`,
    tpopkontrzaehl: this.tpopkontrzaehlFolder && pathElements[11] ? pathElements[11] : null,
    tpopfreiwkontrFolder: this.tpop && pathElements[8] && pathElements[8] === `Freiwilligen-Kontrollen`,
    tpopfreiwkontr: this.tpopfreiwkontrFolder && pathElements[9] ? pathElements[9] : null,
    tpopberFolder: this.tpop && pathElements[8] && pathElements[8] === `Kontroll-Berichte`,
    tpopber: this.tpopberFolder && pathElements[9] ? pathElements[9] : null,
    tpopBeobzuordnungFolder: this.tpop && pathElements[8] && pathElements[8] === `zugeordnete-Beobachtungen`,
    tpopBeobzuordnung: this.tpopBeobzuordnungFolder && pathElements[9] ? pathElements[9] : null,
  }
}
